#!/bin/zsh
# ============================================================
# 生成 /Users/liuhao/Applications/DeviceManager.app macOS App Bundle
# 覆盖重建，确保启动器指向新项目路径 /Users/liuhao/work/DeviceManager/
# Usage: cd /Users/liuhao/work/DeviceManager && ./scripts/build_app.sh
# ============================================================
set -e
PROJ="/Users/liuhao/work/DeviceManager"
APP="/Users/liuhao/Applications/DeviceManager.app"
PY="/Users/liuhao/.pyenv/versions/3.12.4/bin/python3"

echo "清理旧 App（如有）..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

echo "复制 Info.plist + 图标..."
cp "$PROJ/app/Info.plist" "$APP/Contents/"
cp "$PROJ/resources/DM.icns" "$APP/Contents/Resources/"

echo "写入 Launcher 脚本（指向新项目 bin/device_manager.py）..."
cat > "$APP/Contents/MacOS/DeviceManager" <<EOF
#!/bin/zsh
# Auto-generated by scripts/build_app.sh
PY="$PY"
SCRIPT="$PROJ/bin/device_manager.py"
export PATH="/Users/liuhao/.pyenv/versions/3.12.4/bin:/usr/local/bin:/opt/homebrew/bin:\$PATH"
export DEVICE_MANAGER_HOME="$PROJ"
exec "\$PY" "\$SCRIPT" "\$@"
EOF
chmod +x "$APP/Contents/MacOS/DeviceManager"

echo ""
echo "✅ 构建完成 → $APP"
echo "启动命令: open $APP"
